# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98cdf59c655e0a201d14ceb2c946634845ebabb860709ec2fa1eb597de821bb2f2e1118df221b7879b0dfe97ec270a4171f3c06be746e6a692839a107cb5d034

test:
  secret_key_base: c15451bfed26d5cae68a0fe4e878af49dca4a5dc9abfa97d897bef90ff6c6a593f375f70bda6526d8cb37d5c9eb51b8e9771c1943d41e5e6a946232572f3da37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
